/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CartButton: typeof import('./src/components/product-details/CartButton.vue')['default']
    CartPageItem: typeof import('./src/components/CartPageItem.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FooterComponent: typeof import('./src/components/layouts/FooterComponent.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HomeSkeleton: typeof import('./src/components/skeletons/HomeSkeleton.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    Navbar: typeof import('./src/components/layouts/Navbar.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductImage: typeof import('./src/components/product-details/ProductImage.vue')['default']
    ProductInfo: typeof import('./src/components/product-details/ProductInfo.vue')['default']
    ProductNavbar: typeof import('./src/components/product-details/ProductNavbar.vue')['default']
    ProductVariantsForm: typeof import('./src/components/product-details/ProductVariantsForm.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    ShippingMethod: typeof import('./src/components/order-summary/ShippingMethod.vue')['default']
    ShippingSummary: typeof import('./src/components/order-summary/ShippingSummary.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SortPopup: typeof import('./src/components/SortPopup.vue')['default']
    Spinner: typeof import('./src/components/utils/Spinner.vue')['default']
    StoreHomeSkeleton: typeof import('./src/components/skeletons/StoreHomeSkeleton.vue')['default']
    SummaryItem: typeof import('./src/components/order-summary/SummaryItem.vue')['default']
    SummaryTotal: typeof import('./src/components/order-summary/SummaryTotal.vue')['default']
    SwiperCarousel: typeof import('./src/components/SwiperCarousel.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToastSuccess: typeof import('./src/components/utils/ToastSuccess.vue')['default']
  }
}
