/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FooterComponent: typeof import('./src/components/layouts/FooterComponent.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    Navbar: typeof import('./src/components/layouts/Navbar.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductNavbar: typeof import('./src/components/product/ProductNavbar.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SwiperCarousel: typeof import('./src/components/SwiperCarousel.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
